# Add one stanza below for each file or file pattern.
# Using a simple string will exactly match a single file
# Using a regular expression will result in all files that match the pattern being uploaded - more below re regex usage
files:
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_B1_AirVars\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_B1_Dendros\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_B1_SHFplates\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_B1_SoilVars\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_B[2-3]_sap_HeatPulsers\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_B[2-3]_sap_Therminfo\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_T1_fast_CO2\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: daily
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_T1_general\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_T1_Pair\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_T1_Rain\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R[1-6]_T1_ts_data\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: daily
  -
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    file: !ruby/regexp /\AFACE_R3_T1_flux\.dat\Z/
    destination: 
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    rotate: monthly
    