# url to POST to
api_endpoint: https://jp-dc21-staging.intersect.org.au/data_files/api_create

# specify any parameters to be sent with every POST, these will be added to the multipart POST for all files
# this might be used to provide authentication information if tokens are being used
common_parameters:
  auth_token: PSEsmywGqiEMyVni5r54
  
#the name of the file part parameter to send in the multipart post
file_parameter_name: file

# Add one stanza below for each file or file pattern.
# Using a simple string will exactly match a single file
# Using a regular expression will result in all files that match the pattern being uploaded - more below re regex usage
files:
  -
    #directory where the file will be found
    source_directory: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
    #filename or regex
    file: FACE_AUTO_R1_SOILVARS_R_20130831.dat
    #transfer to path - directory to move files to after successful upload
    transfer_to_directory: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/done
    # specify any additional file-specific POST parameters to send with the file, these will be added to the multipart POST
    file_parameters:
      description: some desc
      type: RAW
      experiment_id: 21
