# --File renaming script to be used in conjunction with the HIEv 'Upload to PC' scripts for those circumstances 
# --when the file needs to be renamed between what an instrument produces and what should be uploaded into HIEv
# 
# --Author : Gerard Devine (g.devine@uws.edu.au)
# --Date   : August 2013
#----------------------------------------------------------------------------------------------------------------

# location of files to be renamed (i.e. normally the UploadPending directory)
source_directory: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending

# Add one stanza below for each file or file pattern.
# Using a simple string will exactly match a single file
# Using a regular expression will result in all files that match the pattern being renamed

files:
  -  
    file: !ruby/regexp /\AFACE_R[1-6]_(B|T)[1-9]{1}_[a-zA-Z0-9]*_[0-9]{8}\.dat\Z/
    renamer_routine: 1
  -  
    file: !ruby/regexp /\AFACE_R[1-6]_(B|T)[1-9]{1}_[a-zA-Z0-9]*_[a-zA-Z0-9]*_[0-9]{8}\.dat\Z/
    renamer_routine: 2
    
    