# --File renaming script to be used in conjunction with the HIEv 'Upload to PC' scripts for those circumstances 
# --when the file needs to be renamed between what an instrument produces and what should be uploaded into HIEv
# 
# --Author : Gerard Devine (g.devine@uws.edu.au)
# --Date   : August 2013
#----------------------------------------------------------------------------------------------------------------


# Add one stanza below for each file or file pattern.
# Using a simple string will exactly match a single file
# Using a regular expression will result in all files that match the pattern being renamed - more below re regex usage

#location of files to be renamed (i.e. normally the UploadPending directory)
source_directory: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending

files:
  -    
    #filename or regex to be renamed
    file: !ruby/regexp /\AFACE_R[1-6]_B1_AirVars_[0-9]{8}\.dat\Z/
    #renamer routine - which renamer routine to use
    renamer_routine: 1
  -
    file: !ruby/regexp /\AFACE_R[1-6]_B1_Dendros_[0-9]{8}\.dat\Z/
    renamer_routine: 1    
  -
    file: !ruby/regexp /\AFACE_R[1-6]_B1_SHFplates_[0-9]{8}\.dat\Z/
    renamer_routine: 1
  -
    file: !ruby/regexp /\AFACE_R[1-6]_B1_SoilVars_[0-9]{8}\.dat\Z/
    renamer_routine: 1
  -
    file: !ruby/regexp /\AFACE_R[1-6]_B[2-3]_sap_HeatPulsers_[0-9]{8}\.dat\Z/
    renamer_routine: 2
  -
    file: !ruby/regexp /\AFACE_R[1-6]_B[2-3]_sap_Therminfo_[0-9]{8}\.dat\Z/
    renamer_routine: 2
  -
    file: !ruby/regexp /\AFACE_R[1-6]_T1_fast_CO2_[0-9]{8}\.dat\Z/
    renamer_routine: 2
  -
    file: !ruby/regexp /\AFACE_R[1-6]_T1_general_[0-9]{8}\.dat\Z/
    renamer_routine: 1
  -
    file: !ruby/regexp /\AFACE_R[1-6]_T1_Pair_[0-9]{8}\.dat\Z/
    renamer_routine: 1
  -
    file: !ruby/regexp /\AFACE_R[1-6]_T1_Rain_[0-9]{8}\.dat\Z/
    renamer_routine: 1
  -
    file: !ruby/regexp /\AFACE_R[1-6]_T1_ts_data_[0-9]{8}\.dat\Z/
    renamer_routine: 2
  -
    file: !ruby/regexp /\AFACE_R3_T1_flux_[0-9]{8}\.dat\Z/
    renamer_routine: 1
