# Add one stanza below for each file or file pattern.
# Using a simple string will exactly match a single file
# Using a regular expression will result in all files that match the pattern being uploaded - more below re regex usage
files:
  -
    #directory where the file will be found
    path: /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet
    #filename (can include regular expressions)
    file: FACE_R1_B1_SoilVars.dat
    #The directories where files will be placed. At least one is required
    destination: 
      #The first destination directory is compulsory. 
      #It specifies the destination for files to be placed when they are ready for upload.
      #The transfer script will use this directory as its source file, and perform the upload to DC21.
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/UploadPending
      #additional destinations can be specified for managing backups.
      #The behaviour of file rotation or 'backing up' is defined by the rotate value below
      - /home/gerarddevine/dev/ror/restful-api-uploader/test_data/LoggerNet/Backups/YYYYMMDD_HHMMSS
    #The rotate parameter can be set to 'daily', 'weekly' or 'monthly'.
    #The value determines how frequently files are backed-up and rotated through destination directories.
    #A datestamp will be automatically appended to each file, which signifies the next rotation date.
    #It is also permissibl to leave this field blank, in which case no datestamp will be appended,
    rotate: monthly
